### ISSUE TITLE
Password decryptor.

### ISSUE THREAD

**Issue by EverWinter23** [zephyr2403/autologin#1]
Anyone that has the decryptor can decrypt the password easily. Can't you use Key derivation and key stretching algorithms which are designed for secure password hashing.
[https://docs.python.org/3.6/library/hashlib.html#module-hashlib](url)

**Comment by zephyr2403** [comment]
In general, the whole point of hashing is that it can't be undone. That's not required here. Program needs to decrypt the password stored in the database because it sends the password to DOM elements.
